### ISSUE TITLE
Terrible profile picture

### ISSUE THREAD

**Issue by LishaSweetz** [dannygtech/mido-discord#2]
Not able to read it, too bright and white.
Teeny text. Needs a better developer xD (jk)

**Comment by HazryG** [comment]
yes it needs a better developer this one is bad

#jellzisanerd

**Comment by dannygtech** [comment]
I like the white and black, mido is supposed to represent a "futuristic" style.. will work on making it better though. 

Thanks! :)

**Comment by LishaSweetz** [comment]
#jellzneedsalife
xD

**Comment by dannygtech** [comment]
):

**Comment by LishaSweetz** [comment]
just kidding. Discord bots start out terrible, end up famous

**Comment by dannygtech** [comment]
The profile picture doesn't really affect the functionality of the bot anyway... o.O
